/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartFrame.java
 *
 * Created on Apr 22, 2009, 3:40:19 PM
 */

package PasswordApp;

import java.awt.Dialog;

import PasswordAPI_Implemented.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bioapi.BioAPIException;
import org.bioapi.Framework;
import org.bioapi.template.FrameworkFactory;

/**
 *
 * @author UPEK
 */
public class StartFrame extends MyDialog {

	// Variable passed from PasswordApps to RmiClient
	private String serverIp = ""; // the service provider you choosed
	private String userName = ""; // the user name you login
	
	//  Server IP getter
    public String getServerIp() {
        return serverIp;
    }
	//  User name getter
    public String getUserName() {
        return userName;
    }
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    PasswordBFP p= null;

    /** Creates new form StartFrame */
    public StartFrame() {
        initComponents();
        setModal(true);
        setVisible(true);
    }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextfield1 = new javax.swing.JTextField(15);//ip is 15 digits maximum including "."

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Enroll");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        
        jLabel1.setFont(new java.awt.Font("Impact", 0, 20)); // Form Title
        jLabel1.setText("<html>Biometric&nbsp;Face&nbsp;Identification<br />Service Access Panel<br/><font color='red'><br />Enter Host to Login</font></html>");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // IP title and input
        jLabel2.setText("Enter one of the Service Host IP/HostName:");
        jTextfield1.setFont(new java.awt.Font("Impact", 0, 20)); // IP title and input
        jTextfield1.setText("5.150.112.12");
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jTextfield1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addComponent(jTextfield1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setBounds(300, 70, 450, 370); // Left margin, top margin, width, height
    }// </editor-fold>//GEN-END:initComponents
       private PasswordBFP local()
       {
           try
           {
           Main m = new Main();
           Framework f = FrameworkFactory.createInstance("2.0J");
		   f.getComponentRegistry().install(org.bioapi.ComponentRegistry.Action.INSTALL, m.getBSP());
           PasswordBFP bfp = new PasswordBFP((PasswordAttachSession)m.getBSP().newAttachSession());
		   f.getComponentRegistry().install(org.bioapi.ComponentRegistry.Action.INSTALL, bfp);
           return bfp;
           }
       
            catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}
            return null;
       }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //new PasswordEntry().setbfp(p);
       // setVisible(false);
        try{
        userName = local().Verify(); // change Verify() in PasswordBFP.java to allow to get the user name
        if (userName!=null) {
                JOptionPane.showMessageDialog(null, "<html>Login Successful. Your ID/Password is Valid. <br /><br /><font color='green'>Your connection is now permitted to the Face Matcher Service!</font></html>");
                // permission granted to use MainWindows (quit StartFrame first)
                serverIp = jTextfield1.getText();
                //System.out.println(userName);
                this.dispose();
        } else {
                JOptionPane.showMessageDialog(null, "<html>Login Failed. Your Login is Invalid.<br /><br /><font color='red'>For Secutiry Reason, this application is now terminated!</font>");
                // kill it and MainWindows will not run as well
                System.exit(1);
            }
        }
        catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}

		
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // setVisible(false);
        try{
        if (local().Enroll()) {
                JOptionPane.showMessageDialog(null, "Login Details successfully entered in Database");
            } else {
                JOptionPane.showMessageDialog(null, "Username already exists");
            
            }
        }
        catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartFrame dialog = new StartFrame();
                dialog.setVisible(true);
        		// Custom JDialog Windows close to Exit
                dialog.setDefaultCloseOperation(dialog.EXIT_ON_CLOSE);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextfield1;
    // End of variables declaration//GEN-END:variables

}