/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StartFrame.java
 *
 * Created on Apr 22, 2009, 3:40:19 PM
 */

package PasswordApp;

import PasswordAPI_Implemented.*;
import javax.swing.JOptionPane;
import org.bioapi.BioAPIException;
import org.bioapi.Framework;
import org.bioapi.template.FrameworkFactory;

/**
 *
 * @author UPEK
 */
public class StartFrame extends javax.swing.JDialog {

    PasswordBFP p= null;

    /** Creates new form StartFrame */
    public StartFrame() {
        initComponents();
        setModal(true);
        setVisible(true);
    }

   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("VERIFY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENROLL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("BioAPI Password Application");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        setBounds(400, 400, 390, 212);
    }// </editor-fold>//GEN-END:initComponents
       private PasswordBFP local()
       {
           try
           {
           Main m = new Main();
           Framework f = FrameworkFactory.createInstance("2.0J");
		   f.getComponentRegistry().install(org.bioapi.ComponentRegistry.Action.INSTALL, m.getBSP());
           PasswordBFP bfp = new PasswordBFP((PasswordAttachSession)m.getBSP().newAttachSession());
		   f.getComponentRegistry().install(org.bioapi.ComponentRegistry.Action.INSTALL, bfp);
           return bfp;
           }
       
            catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}
            return null;
       }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //new PasswordEntry().setbfp(p);
       // setVisible(false);
        try{
        if (local().Verify()) {
                JOptionPane.showMessageDialog(null, "Login Successful");
               
            } else {
                JOptionPane.showMessageDialog(null, "Login Failed");
              
            }
        }
        catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}

		
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      // setVisible(false);
        try{
        if (local().Enroll()) {
                JOptionPane.showMessageDialog(null, "Login Details successfully entered in Database");
             
            } else {
                JOptionPane.showMessageDialog(null, "Username already exists");
            
            }
        }
        catch(BioAPIException e)
		{
			System.err.println(e.getMessage());
		}
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StartFrame dialog = new StartFrame();
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
